# .github/workflows/deploy-to-s3.yml

name: Deploy to S3

on:
  workflow_call:
    secrets:
      AWS_REGION:
        required: true
      AWS_ROLE:
        required: true
    inputs:
      s3-bucket:
        required: true
        type: string
      working-directory:
        required: true
        type: string
      build-command:
        type: string
        default: npx nx build client --prod
permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy Nx React App
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: gh-actions-${{ github.run_id }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.working-directory }}

      - name: Build Nx React App
        run: ${{ inputs.build-command }}
        working-directory: ${{ inputs.working-directory }}

      - name: Deploy to S3
        run: |
          aws s3 sync ${{ inputs.working-directory }}/dist/apps/client s3://${{ inputs.s3-bucket }} --delete
